echo ">>>>> cppstd_invalid.py (default)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/default
echo ">>>>> cppstd_invalid.py (cpp98)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/cpp98
echo ">>>>> cppstd_invalid.py (cpp11)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/cpp11
echo ">>>>> cppstd_invalid.py (cpp14)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/cpp14
echo ">>>>> cppstd_invalid.py (cpp17)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/cpp17
echo ">>>>> cppstd_invalid.py (cpp20)"
conan package_id advanced/cppstd_invalid.py --profile=profiles/cpp20
