echo ">>>>> compatible.py (default)"
conan package_id basic/compatible.py --profile=profiles/default
echo ">>>>> compatible.py (cpp98)"
conan package_id basic/compatible.py --profile=profiles/cpp98
echo ">>>>> compatible.py (cpp11)"
conan package_id basic/compatible.py --profile=profiles/cpp11
echo ">>>>> compatible.py (cpp14)"
conan package_id basic/compatible.py --profile=profiles/cpp14
echo ">>>>> compatible.py (cpp17)"
conan package_id basic/compatible.py --profile=profiles/cpp17
echo ">>>>> compatible.py (cpp20)"
conan package_id basic/compatible.py --profile=profiles/cpp20
